---
title: "OPL_OPEN_TIME"
format: html
editor: source
---

## Packages
```{r}

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

# librarian downloads, if not already downloaded, and reads in needed packages
librarian::shelf(tidyverse, here, DBI, odbc)


date <- Sys.Date()

```



```{r}
tryCatch({
  db_connection_pg <- DBI::dbConnect(odbc::odbc(),  # Establish a database connection using ODBC for the playground database
                                     Driver = "SnowflakeDSIIDriver",  # Specify the Snowflake ODBC driver
                                     Server = "hawaiianair.west-us-2.azure.snowflakecomputing.com",  # Server address
                                     WAREHOUSE = "DATA_LAKE_READER",  # Specify the Snowflake warehouse
                                     Database = "PLAYGROUND",  # Specify the database name
                                     UID = "jacob.eisaguirre@hawaiianair.com",  # User ID for authentication
                                     authenticator = "externalbrowser")  # Use external browser for authentication
  print("Database Connected!")  # Print success message if connection is established
}, error = function(cond) {
  print("Unable to connect to Database.")  # Print error message if connection fails
})

# Set schema and retrieve data from `AA_FINAL_PAIRING` table
dbExecute(db_connection_pg, "USE SCHEMA CREW_ANALYTICS") 

```

```{r}
fp_q <- paste("select * from AA_FINAL_PAIRING where FLIGHT_DATE >'", date,"';")

raw_fp <- dbGetQuery(db_connection_pg, fp_q)


```


## Pilots - CA & FO
```{r}


ot_pilot_pairings <- raw_fp %>% 
  select(c(1:11)) %>% 
  filter(!DEPARTING_CITY %in% c("BOS", "AUS", "HND", "KIX", "NRT", "ICN", "FUK", "SYD", "AKL", "JFK", "CRK"),
         PAIRING_POSITION %in% c("CA", "FO")) %>% 
  mutate(n = 0) %>% 
  group_by(FLIGHT_DATE, FLIGHT_NO, DEPARTING_CITY, ARRIVAL_CITY, SCHED_DEPARTURE_TIME, SCHED_ARRIVAL_TIME) %>% 
  complete(
    PAIRING_POSITION = c("CA", "FO"), 
    fill = list(n = 1)
  ) %>% 
  distinct() %>% 
  pivot_wider(names_from = PAIRING_POSITION, values_from = n) %>% 
  fill(CA, FO, PAIRING_NO, PAIRING_DATE, SCHED_DEPARTURE_DATE, SCHED_ARRIVAL_DATE, .direction = "downup") %>%  # fill down within each group
  filter(CA == 1 | FO == 1) %>% 
  distinct()
  

  
  ### OLD
  
  reframe(n = n(),
          PAIRING_NO = PAIRING_NO,
          PAIRING_DATE = PAIRING_DATE,
          EQUIPMENT = EQUIPMENT) %>% 
  filter(n <= 1) %>% 
  select(FLIGHT_DATE, FLIGHT_NO, DEPARTING_CITY, ARRIVAL_CITY, SCHED_DEPARTURE_TIME, SCHED_ARRIVAL_TIME, PAIRING_NO, PAIRING_DATE)

p_counts <- raw_fp %>% 
  filter(PAIRING_POSITION %in% c("CA", "FO")) %>% 
  select(FLIGHT_DATE, FLIGHT_NO, PAIRING_DATE, PAIRING_NO, PAIRING_POSITION, 
         EQUIPMENT, DEPARTING_CITY, ARRIVAL_CITY, SCHED_ARRIVAL_TIME, SCHED_DEPARTURE_TIME) %>% 
  group_by(FLIGHT_DATE, FLIGHT_NO, PAIRING_NO, PAIRING_POSITION, 
           EQUIPMENT, DEPARTING_CITY, ARRIVAL_CITY, SCHED_ARRIVAL_TIME, SCHED_DEPARTURE_TIME) %>% 
  distinct() %>% 
  semi_join(ot_pilot_pairings, by = c("FLIGHT_DATE", "FLIGHT_NO", "PAIRING_NO", "DEPARTING_CITY", "ARRIVAL_CITY")) %>% 
  mutate(PAIRING_PRESENT = 0) %>%
  pivot_wider(names_from = PAIRING_POSITION, values_from = PAIRING_PRESENT, values_fill = 1) %>% 
  mutate(across(c("CA", "FO"), ~ if_else(is.na(.), 1, .))) %>%
  ungroup() %>% 
  filter(CA == 1 |
         FO == 1) %>% 
  mutate(RO = NA)



```

## Pilots - RO
```{r}

ot_ro_pairings <- raw_fp %>% 
  filter(DEPARTING_CITY %in% c("BOS", "AUS", "HND", "KIX", "NRT", "ICN", "FUK", "SYD",
                              "AKL", "JFK", "CRK"),
         PAIRING_POSITION %in% c("CA", "FO", "RO"),
         !EQUIPMENT == "33Y") %>% 
  select(FLIGHT_DATE, FLIGHT_NO, DEPARTING_CITY, ARRIVAL_CITY, 
         SCHED_DEPARTURE_TIME, SCHED_ARRIVAL_TIME, PAIRING_POSITION) %>% 
  mutate(n = 0) %>%
  group_by(FLIGHT_DATE, FLIGHT_NO, DEPARTING_CITY, ARRIVAL_CITY, SCHED_DEPARTURE_TIME, SCHED_ARRIVAL_TIME) %>% 
  complete(
    PAIRING_POSITION = c("CA", "FO", "RO"), 
    fill = list(n = 1)
  ) %>% 
  distinct() %>% 
  pivot_wider(names_from = PAIRING_POSITION, values_from = n) %>% 
  filter(RO == 1)

  ### OLD

reframe(n = n(),
          PAIRING_NO = PAIRING_NO,
          PAIRING_DATE = PAIRING_DATE,
          EQUIPMENT = EQUIPMENT) %>% 
  filter(!EQUIPMENT == "33Y",
         n <= 2) %>% 
  distinct() %>% 
  mutate(RO = 1,
         CA = 0,
         FO = 0) %>% 
  select(!n)



final_open_p_counts <- rbind(p_counts, ot_ro_pairings)

```


## FA
```{r}

ot_fa_pairings <- raw_fp %>% 
  filter(CREW_INDICATOR == "FA")%>% 
  group_by(FLIGHT_DATE, FLIGHT_NO, DEPARTING_CITY, ARRIVAL_CITY, SCHED_DEPARTURE_TIME, SCHED_ARRIVAL_TIME) %>% 
  reframe(n = n(),
          PAIRING_NO = PAIRING_NO,
          EQUIPMENT = EQUIPMENT)

```


#### OLD
## Packages
```{r}

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

# librarian downloads, if not already downloaded, and reads in needed packages
librarian::shelf(tidyverse, here, DBI, odbc)



```



```{r}
tryCatch({
  db_connection <- DBI::dbConnect(odbc::odbc(),  # Establish a database connection using ODBC for the playground database
                                     Driver = "SnowflakeDSIIDriver",  # Specify the Snowflake ODBC driver
                                     Server = "hawaiianair.west-us-2.azure.snowflakecomputing.com",  # Server address
                                     WAREHOUSE = "DATA_LAKE_READER",  # Specify the Snowflake warehouse
                                     Database = "ENTERPRISE",  # Specify the database name
                                     UID = "jacob.eisaguirre@hawaiianair.com",  # User ID for authentication
                                     authenticator = "externalbrowser")  # Use external browser for authentication
  print("Database Connected!")  # Print success message if connection is established
}, error = function(cond) {
  print("Unable to connect to Database.")  # Print error message if connection fails
})

# Set schema and retrieve data from `AA_FINAL_PAIRING` table
dbExecute(db_connection, "USE SCHEMA CREW_ANALYTICS") 

```

```{r}
ot_q <- "select * from CT_OPEN_TIME where PAIRING_DATE BETWEEN '2024-11-01' AND '2024-11-30';"

raw_ot <- dbGetQuery(db_connection, ot_q)


```


```{r}


clean_ot <- raw_ot %>% 
  filter(CREW_INDICATOR == "P") %>% 
  mutate(updated_dt = paste(UPDATE_DATE, UPDATE_TIME, sep = " ")) %>% 
  mutate(RESERVE_POSITION = ifelse(RESERVE_POSITION %in% c("CA", "FO", "RO", "FA"),
                                   RESERVE_POSITION, 
                                   "FA"),
         BASE = if_else(BASE == "HAL", "HNL", BASE),
        ) %>% 
  group_by(PAIRING_NO, PAIRING_DATE, RESERVE_POSITION) %>% 
  filter(updated_dt == max(updated_dt),
         ORIGIN == "M",
         is.na(PAIRING_ASSIGNMENT_CODE)) %>% 
  rename(PAIRING_POSITION = RESERVE_POSITION) %>% 
  select(CREW_INDICATOR, PAIRING_NO, PAIRING_DATE, BASE, PAIRING_POSITION)%>%
  mutate(n=1) %>% 
  pivot_wider(names_from = PAIRING_POSITION, values_from = n) %>% 
  mutate(across(c("CA", "FO"), ~ if_else(is.na(.), 0, .)))



```


